# Generated by Django 5.1.2 on 2024-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Accountnum', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('income', models.FloatField()),
                ('Loanam', models.FloatField()),
                ('Aadharnum', models.IntegerField(primary_key='Aadharnum', serialize=False)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
